### ISSUE TITLE
App crashes as soon as a new user register or when a logged in user logout

### ISSUE THREAD

**Issue by pranavtartey** [pranavtartey/BlogProject#1]
The issue is with the req.login(), req.logout() builtin method in passport js. You can find the issue in the following lines:
1) controllers/user.js line: 8.
2) controllers/user.js line: 32.

**Comment by BhavyaMPatel** [comment]
I see the error it says that cannot send header after it sent to the client it means on line no 10 you use res.redirect("/blog") but on line no 15 you again send res.status(200) most probebly thats make error you can check out that onces

**Comment by BhavyaMPatel** [comment]
and same for logout route also
